version: "3.8"

services:
  db:
    image: postgres:16
    container_name: wasaProject_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: wasaText
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: wasa_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: chat_user
      DB_PASSWORD: chat_pass
      DB_NAME: chat_db

  frontend:
    build: ./frontend
    container_name: wasa_frontend
    depends_on:
      - backend
    ports:
      - "4173:4173"

volumes:
  db_data:
